version: '3.3'
services:
    admin-web:
        container_name: admin-web
        image: bavaan-admin-web:latest
        build:
            context: .
            dockerfile: .deploy/admin-web/Dockerfile
        environment:
            NODE_ENV: production
        restart: on-failure
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.venduremarketplace.rule=Host(`vendure-marketplace.com`)"
            - "traefik.http.routers.venduremarketplace.entrypoints=web"
            - "traefik.http.services.venduremarketplace.loadbalancer.server.port=8080"
            - "traefik.docker.network=proxy"
        ports:
            - 8080
            - 3000
            - 9000
        networks:
            - proxy
            - internal
            - overlay
volumes:
    root_node_modules:
    certificates:

networks:
    proxy:
        external:
            name: proxy
    internal:
        driver: bridge
    overlay:
        driver: bridge