version: '3.3'
services:
    # admin-web:
    #     container_name: admin-web
    #     image: bavaan-admin-web:latest
    #     build:
    #         context: .
    #         dockerfile: .deploy/admin-web/Dockerfile
    #     environment:
    #         NODE_ENV: production
    #     restart: on-failure
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.venduremarketplace.rule=Host(`vendure-marketplace.localhost`)"
    #         - "traefik.http.routers.venduremarketplace.entrypoints=web"
    #         - "traefik.http.services.venduremarketplace.loadbalancer.server.port=8080"
    #         - "traefik.docker.network=proxy"
    #     ports:
    #         - 8080
    #         - 3000
    #         - 9000
    #     networks:
    #         - proxy
    #         - internal
    #         - overlay
    mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog.vendure-marketplace.com'
      logging:
        driver: 'none'  # disable saving logs
      ports:
        - "1025:1025"
        - "8025:8025"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.venduremarketplacemail.rule=Host(`mailhog.vendure-marketplace.localhost`)"
        - "traefik.http.routers.venduremarketplacemail.entrypoints=web"
        - "traefik.http.services.venduremarketplacemail.loadbalancer.server.port=8025"
        - "traefik.docker.network=proxy"
      networks:
        - proxy
        - internal
    db:
        image: mysql
        container_name: 'mysql.vendure-marketplace.com'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3346:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - internal

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: 'db.vendure-marketplace.com'
        restart: always
        ports:
            - '80'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.venduremarketplacedb.rule=Host(`db.vendure-marketplace.localhost`)"
            - "traefik.http.routers.venduremarketplacedb.entrypoints=web"
            - "traefik.http.services.venduremarketplacedb.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - proxy
            - internal
volumes:
    root_node_modules:
    certificates:

networks:
    proxy:
        external:
            name: proxy
    internal:
        driver: bridge
    overlay:
        driver: bridge