import {gql} from 'apollo-server-core';

export const adminApiExtensions = gql`
    
    type ShippingCountryPrice implements Node {
        id: ID!
        country_code: String!
        country_name: String!
        price: Float!
    }

    type ShippingCountryPriceList implements PaginatedList {
        items: [ShippingCountryPrice!]!
        totalItems: Int!
    }

    input CreateShippingCountryInput {
        country_code: String!
        price: Float!
    }

    input UpdateShippingCountryInput {
        id: ID!
        price: Float!
    }

    # generated by generateListOptions function
    input ShippingCountryListOptions
    
    extend type Mutation {
        createShippingCountry(input: CreateShippingCountryInput!): ShippingCountryPrice!
        updateShippingCountry(input: UpdateShippingCountryInput!): ShippingCountryPrice!
        deleteShippingCountry(id: ID!): DeletionResponse!
    }
    extend type Query {
        shippingCountry(id: ID!): ShippingCountryPrice
        shippingCountries(options: ShippingCountryListOptions!): ShippingCountryPriceList!
    }
    
`;