import gql from 'graphql-tag';

export const ORDER_FRAGMENT = gql`
    fragment Order on Order {
        id
        createdAt
        updatedAt
        code
        state
        active
        customer{
            id
            createdAt
            updatedAt
            title
            firstName
            lastName
            phoneNumber
            emailAddress
        }
        shippingAddress{
            fullName
            company
            streetLine1
            streetLine2
            city
            province
            postalCode
            country
            countryCode
            phoneNumber
        }
        billingAddress{
            fullName
            company
            streetLine1
            streetLine2
            city
            province
            postalCode
            country
            countryCode
            phoneNumber
        }
        lines{
            id
            createdAt
            updatedAt
            quantity
            totalPrice
            productVariant{
                name
                sku
            }
            unitPrice
            unitPriceWithTax
            featuredAsset{
                preview
            }
        }
        adjustments{
            adjustmentSource
            description
            amount
        }
        couponCodes
        promotions{
            id
            createdAt
            updatedAt
            startsAt
            endsAt
            couponCode
            perCustomerUsageLimit
            name
            enabled
        }
        payments{
            id
            createdAt
            updatedAt
            method
            amount
            state
            transactionId
            errorMessage
        }
        fulfillments{
            id
            createdAt
            updatedAt
            method
            trackingCode
        }
        totalQuantity
        subTotalBeforeTax
        subTotal
        currencyCode
        shipping
        shippingWithTax
        shippingMethod{
            id
            createdAt
            updatedAt
            code
            description
        }
        totalBeforeTax
        total
        customFields
    }
`;